"""
Step 4 of the GSTR-1 pipeline — write the beta register into the EXACT government
GSTR-1 Excel workbook.

The template is regenerated byte-for-byte from the AICA_EXACT_XLSX_CAPSULE, then
opened and filled starting at row 5 (rows 1-4 are the frozen header/summary block).
Only data cells are written; headers, formulas, styles and protection are left
untouched.

Scope: the four active buckets — B2B, B2CL, B2CS, Nil-rated — land in the
'b2b,sez,de', 'b2cl', 'b2cs' and 'exemp' sheets respectively.
"""
from __future__ import annotations
import tempfile
from pathlib import Path
from typing import Any

import openpyxl

from app.filing.gstr1.constants import B2B, B2CL, B2CS, NIL
from app.filing.gstr1_recreate import recreate, CAPSULE_PATH

DATA_START_ROW = 5


def fill(beta_rows: list[dict[str, Any]], output_path: Path) -> Path:
    """
    Regenerate the exact template and fill it with the beta register.
    Returns the path to the written workbook.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # 1. Recreate the exact empty template into a temp file (verifies SHA-256).
    with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as tmp:
        tmp_path = Path(tmp.name)
    try:
        recreate(CAPSULE_PATH, tmp_path)

        # 2. Open and fill.
        wb = openpyxl.load_workbook(tmp_path)
        buckets = _split_buckets(beta_rows)
        _write_b2b(wb["b2b,sez,de"], buckets[B2B])
        _write_b2cl(wb["b2cl"], buckets[B2CL])
        _write_b2cs(wb["b2cs"], buckets[B2CS])
        _write_exemp(wb["exemp"], buckets[NIL])

        wb.save(output_path)
    finally:
        tmp_path.unlink(missing_ok=True)

    return output_path


def _split_buckets(rows: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    out: dict[str, list[dict[str, Any]]] = {B2B: [], B2CL: [], B2CS: [], NIL: []}
    for r in rows:
        out.setdefault(r.get("segregator"), []).append(r)
    return out


def _set(ws, row: int, col: int, value: Any) -> None:
    if value is not None and value != "":
        ws.cell(row=row, column=col, value=value)


# ── b2b,sez,de ─────────────────────────────────────────────────────────────────
# 1 GSTIN | 2 Receiver Name | 3 Invoice No | 4 Invoice date | 5 Invoice Value
# 6 POS | 7 Reverse Charge | 8 Applicable % | 9 Invoice Type | 10 E-Com GSTIN
# 11 Rate | 12 Taxable Value | 13 Cess Amount
def _write_b2b(ws, rows: list[dict[str, Any]]) -> None:
    for i, r in enumerate(rows):
        row = DATA_START_ROW + i
        _set(ws, row, 1, r.get("gstin"))
        _set(ws, row, 2, r.get("particulars"))
        _set(ws, row, 3, r.get("voucher_number"))
        _set(ws, row, 4, r.get("date"))
        _set(ws, row, 5, r.get("invoice_value"))
        _set(ws, row, 6, r.get("pos"))
        _set(ws, row, 7, r.get("reverse_charge"))
        _set(ws, row, 8, r.get("applicable_tax_rate"))
        _set(ws, row, 9, r.get("voucher_type") if _is_note(r) else "Regular B2B")
        _set(ws, row, 10, r.get("ecommerce_gstin"))
        _set(ws, row, 11, r.get("applicable_tax_rate"))
        _set(ws, row, 12, r.get("taxable_value"))
        _set(ws, row, 13, r.get("cess"))


# ── b2cl ───────────────────────────────────────────────────────────────────────
# 1 Invoice No | 2 Invoice date | 3 Invoice Value | 4 POS | 5 Applicable %
# 6 Rate | 7 Taxable Value | 8 Cess Amount | 9 E-Com GSTIN
def _write_b2cl(ws, rows: list[dict[str, Any]]) -> None:
    for i, r in enumerate(rows):
        row = DATA_START_ROW + i
        _set(ws, row, 1, r.get("voucher_number"))
        _set(ws, row, 2, r.get("date"))
        _set(ws, row, 3, r.get("invoice_value"))
        _set(ws, row, 4, r.get("pos"))
        _set(ws, row, 5, r.get("applicable_tax_rate"))
        _set(ws, row, 6, r.get("applicable_tax_rate"))
        _set(ws, row, 7, r.get("taxable_value"))
        _set(ws, row, 8, r.get("cess"))
        _set(ws, row, 9, r.get("ecommerce_gstin"))


# ── b2cs (summary: aggregate by Type / POS / Rate / E-Com) ─────────────────────
# 1 Type | 2 POS | 3 Applicable % | 4 Rate | 5 Taxable Value | 6 Cess | 7 E-Com GSTIN
def _write_b2cs(ws, rows: list[dict[str, Any]]) -> None:
    agg: dict[tuple, dict[str, Any]] = {}
    for r in rows:
        ecom = r.get("ecommerce_gstin")
        typ = "E" if ecom else "OE"
        rate = r.get("applicable_tax_rate")
        pos = r.get("pos")
        key = (typ, pos, rate, ecom)
        entry = agg.setdefault(key, {
            "type": typ, "pos": pos, "rate": rate, "ecom": ecom,
            "taxable": 0.0, "cess": 0.0,
        })
        entry["taxable"] += float(r.get("taxable_value") or 0.0)
        entry["cess"] += float(r.get("cess") or 0.0)

    for i, e in enumerate(agg.values()):
        row = DATA_START_ROW + i
        _set(ws, row, 1, e["type"])
        _set(ws, row, 2, e["pos"])
        _set(ws, row, 3, e["rate"])
        _set(ws, row, 4, e["rate"])
        _set(ws, row, 5, round(e["taxable"], 2))
        _set(ws, row, 6, round(e["cess"], 2) or None)
        _set(ws, row, 7, e["ecom"])


# ── exemp (Nil rated summary) ──────────────────────────────────────────────────
# 1 Description | 2 Nil Rated | 3 Exempted | 4 Non-GST
def _write_exemp(ws, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    total = round(sum(float(r.get("taxable_value") or 0.0) for r in rows), 2)
    row = DATA_START_ROW
    _set(ws, row, 1, "Nil rated supplies")
    _set(ws, row, 2, total)


def _is_note(r: dict[str, Any]) -> bool:
    vt = str(r.get("voucher_type") or "").lower()
    return "credit note" in vt or "debit note" in vt
